### PR TITLE
Bump requirements to fix docker build

### PR DESCRIPTION
**Pull request by joshmoore**
I've been getting notifications from Docker Hub. This should at least silent the failures.

cc: @manics @sbesson

### CODE REVIEW

**Comment by manics** [comment]
This fix seems to be in https://github.com/IDR/pydoop-features/compare/master...openmicroscopy:master, worth merging?

**Comment by joshmoore** [comment]
Pushed for review.

**Comment by manics** [comment]
Looks fine.

The OMERO version needs to be bumped, either in this PR or separately: https://github.com/IDR/pydoop-features/blob/d5603ccba89d5996e42b525390c86d521550a3b9/Dockerfile#L26

Also https://github.com/openmicroscopy/pydoop-features/blob/6f5f03ee7f8e484ecd356a01feeba0bbabe45b2c/Dockerfile#L27

**Comment by joshmoore** [comment]
> The OMERO version needs to be bumped, either in this PR or separately:

Just waiting on the latest version (https://github.com/openmicroscopy/openmicroscopy/pull/5690 etc) then will do so here.

**Comment by joshmoore** [comment]
Pushed & travis green, @manics

**Review by manics — APPROVED** [review]

**Comment by joshmoore** [comment]
Cheers. Merging to end the notifications from Docker Hub. We can decide if this should be released (and as what) separately.

**Pull request merged**
